site_name: ACAP Missing Features Documentation
theme:
  name: material
  palette:
    scheme: slate 
    primary: yellow 

    toggle:
      icon: material/weather-night
      name: Switch to light mode

nav:
  - About: index.md
  - Changelog: change.md
  - Compatibility: compat.md
  - Enable or Disable Features: endis.md
  - Event Trigger: event_trigger.md
  - Features: 
    - Overview: features.md
    - Flow: flow.md
    - Image to SD-Card: img_sdcard.md
    - Metadata Dispatch: metadispatch.md
    - Notifications: notifications.md
    - Occupancy counting: occupancy.md
    - Parking Times: parking_times.md

  - General Settings: general_settings.md
  - Installation: install.md
  - Licensing: licensing.md
  - Support: support.md

extra_css:
  - css/custom.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

copyright: Copyright &copy; Commend Ã–sterreich GmbH 
