site_name: ACAP Missing Features Documentation
theme:
  name: material
  palette:
    scheme: slate
    primary: yellow

    toggle:
      icon: material/weather-night
      name: Switch to light mode

nav:
  - Installation: index.md
  - Limitations: limitations.md
  - Features:
    - Flow:
      - Overview: flow.md
      - Reference: flow/reference.md
      - Input & Output: flow/input_output_nodes.md
      - Logic & Flow Control: flow/logic_nodes.md
      - Data & Math: flow/data_manipulation.md
      - Devices & ANPR: flow/device_nodes.md
      - Timing: flow/timing_nodes.md
      - Network & Protocols: flow/network_nodes.md
      - Database & SQL: flow/database_nodes.md
      - Collections & JSON: flow/collections_nodes.md
      - String & Text: flow/string_nodes.md
      - Storage & SD Card: flow/storage_nodes.md
      - Advanced & Scripting: flow/advanced_nodes.md
      - Composites: flow/composites.md
    - Dashboard: dashboard.md
    - Spot Color Detector: spot_color.md
    - Image to SD-Card: img_sdcard.md
    - Scene Analysis Triggers: scene_analysis.md
    - License Plate List: license_plate_list.md
  - General Settings: general_settings.md
  - Changelog: change.md
  - Video Tutorials: videos.md
  - Support: support.md

extra_css:
  - css/custom.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

copyright: Copyright &copy; Commend Ã–sterreich GmbH
